### ISSUE TITLE
OrdinalIgnoreCase comparison infinite loop in v2.2.0

### ISSUE THREAD

**Issue by El-Gor-do** [tompazourek/NaturalSort.Extension#4]
In v2.2.0, this comparison appears to get stuck in an infinite loop whereas v2.1.0 handles it without any problems.

`StringComparer.OrdinalIgnoreCase.WithNaturalSort().Compare("abc", "Abc")`

**Comment by tompazourek** [comment]
Thanks for the report, it's weird that the tests didn't catch this. I'll check it out.

**Comment by tompazourek** [comment]
I fixed the bug and released it in 2.2.1.

I'm still waiting until NuGet indexes the package I uploaded, it usually takes at least a few minutes.

It should be here when it's done: https://www.nuget.org/packages/NaturalSort.Extension/2.2.1

**Comment by El-Gor-do** [comment]
Thanks, that was quick!
