### ISSUE TITLE
.Net 7

### ISSUE THREAD

**Issue by stein-t** [tompazourek/NaturalSort.Extension#57]
When do plan to release for .Net 7 resp. .Net 8? Thank you.

**Comment by tompazourek** [comment]
The library works fine for .NET 7 and .NET 8, you should be able to install it without any problems.

The target frameworks are more like "minimum versions".

**Comment by tompazourek** [comment]
Closing this issue. Feel free to open a new one in case you have more information (e.g. errors you're experiencing).
